version: '3'
services:
  web:
    image: tu-nombre-de-imagen-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"  # Cambia aquí al nuevo puerto
    deploy:
      replicas: 4
